version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./myapp:/myapp
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000
